# DEEP LEARNING
## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

In [93]:
# Numpy là thư viện kiểu list
# Vì:
# + numpy nhanh 
# + có nhiều hàm tích hợp dễ sử dụng cho AI
# để sử dụng numpy thì: pip install numpy
import numpy as np

In [94]:
# thử tạo 1 list numpy
python_list = ([1,2,3,4,5])

#chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [95]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [96]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [97]:
# chuyển đổi kiểu dữ liệu 
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [98]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8])# np.array(range(1,9))


In [99]:
x[3]

np.int64(4)

In [100]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
x[0:3]

array([1, 2, 3])

In [101]:
# lấy từ 3 - 8 theo 3 cách
# cacah 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [102]:
# cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [103]:
# cách 3- không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [104]:
# lấy số 3 vầ số 5
x[2], x[4]
x[2:5:2]

array([3, 5])

In [105]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [106]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
# lấy số 2 
np_list[0,1]

np.int64(2)

In [108]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [109]:
# layass 3 4 5 6 
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [110]:
# cách 2
np_list[[1,2]]


array([[3, 4],
       [5, 6]])

In [111]:
# cách3
np_list[1:3]

array([[3, 4],
       [5, 6]])

In [112]:
#cách 4
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [113]:
# lấy 1 3 5 
np_list[:,0]

array([1, 3, 5])

In [114]:
np_list[::2,0]

array([1, 5])

In [115]:
x = [[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
# layass 2 6 10 14
np_list[:,1]


array([ 2,  6, 10, 14])

In [117]:
# layass 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [118]:
# lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [119]:
# lấy 16 15 14 13
np_list[[3,3,3,3],[3,2,1,0]]
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [120]:
np_list[-1, -1::-1]


array([16, 15, 14, 13])

# BTVN thú vị

# cho ma trận = [[99,99,99],[99,99,99],[99,99,99]]

# hãy tưởng tượng ô 99 trống 
# giả sử  0 là o
# giả sử 1 là x
# lấy đầu vào từ phía x và phí o luôn phiên 
# Nếu đầu vào từ phía X là (0,0)
# ma trận sẽ trở thành 

# [x,99,99]
# [99,99,99]
# [99,99,99]
# nếu đầu vào từ phía o cũng là (0,0)
# thông báo nhập lại 
# nếu không thì điền vào ma trận

# thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dùng trò chơi


In [121]:
import numpy as np

matrix = np.array([[99, 99, 99],
                   [99, 99, 99],
                   [99, 99, 99]])

current_player = 1
for turn in range(9):
    print("\nMa trận hiện tại:")
    print(matrix)
    name = "x" if current_player == 1 else "o"
    #điền và kiểm tra ô trống
    while True:
        r = int(input(f"Lượt {name}, nhập hàng (0-2): "))
        c = int(input(f"Lượt {name}, nhập cột (0-2): "))
        
        if matrix[r, c] != 99:
            print("Ô này có người đi rồi vui lòng nhập lại")
        else:
            matrix[r, c] = current_player
            break
    #thử thách: Kiểm ái tra thắng 
    win = False
    for i in range(3):
        #kiểm tra hàng ngang và cột dọc
        if sum(matrix[i, :]) == 3 * current_player or sum(matrix[:, i]) == 3 * current_player:
            win = True
    #kiểm tra đường chéo
    if matrix[0,0] + matrix[1,1] + matrix[2,2] == 3 * current_player: win = True
    if matrix[0,2] + matrix[1,1] + matrix[2,0] == 3 * current_player: win = True
    
    if win:
        print("\n", matrix)
        print(f"{name} đã thắng")
        break
    current_player = 1 - current_player
else:
    print("\n", matrix)
    print("Hòa")


Ma trận hiện tại:
[[99 99 99]
 [99 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1 99 99]
 [99 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1  0 99]
 [99 99 99]
 [99 99 99]]

Ma trận hiện tại:
[[ 1  0 99]
 [99 99 99]
 [99  1 99]]

Ma trận hiện tại:
[[ 1  0 99]
 [99 99  0]
 [99  1 99]]

Ma trận hiện tại:
[[ 1  0 99]
 [99 99  0]
 [ 1  1 99]]

Ma trận hiện tại:
[[ 1  0 99]
 [99 99  0]
 [ 1  1  0]]
Ô này có người đi rồi vui lòng nhập lại

Ma trận hiện tại:
[[ 1  0  1]
 [99 99  0]
 [ 1  1  0]]

Ma trận hiện tại:
[[ 1  0  1]
 [99  0  0]
 [ 1  1  0]]

 [[1 0 1]
 [1 0 0]
 [1 1 0]]
x đã thắng


# BTVN 2
# cho y = [[1,2,3],[4,5,6],[7,8,9]]

# LẤY 4 5 6
# lấy 2, 5
# lấy 3,4
# lấy 9,6,3


In [122]:
# BTVN 2
import numpy as np
# cho y = [[1,2,3],[4,5,6],[7,8,9]]
y = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
np_list = np.array(y)
np_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
# LẤY 4 5 6
np_list[1,:]

array([4, 5, 6])

In [124]:
# lấy 2, 5
np_list[[0,1],1]

array([2, 5])

In [125]:
# lấy 9,6,3
np_list[[2,1,0],2]

array([9, 6, 3])

In [126]:
# lấy 3,4
np_list[[0,1], [2,0]]

array([3, 4])

# BTVN 3

# cho x  = [[1,2,3,4,5,6,7,8,9,10]]

# xuata ra cas gias trị chẵn sử dụng if
# xuất ra các giá trị chẵn sử dụng lit comprehension


In [127]:
# BTVN 3
import numpy as np
# cho x  = [[1,2,3,4,5,6,7,8,9,10]]
x = np.array([[1,2,3,4,5,6,7,8,9,10]])
np_list = np.array(x)
# xuất ra các giá trị chẵn sử dụng if
for i in np_list[0]:
    if i % 2 == 0:
        print(i)
# xuất ra các giá trị chẵn sử dụng list comprehension
so_chan = [i for i in np_list[0] if i % 2 == 0]
print(so_chan)

2
4
6
8
10
[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]


In [128]:
np_x = np.arange(10)
np_x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [130]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
idx = [True, True,  True, False,  True, True,  True, False,  True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [132]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# BTVN4
# tạo 1 mảng numpy có kích thức 150 x 5. giả sử mảng này chứa 150 mẫu dữ liệu 
# của sinh vienen  bao gồm chiều cao cân nặng tuổi , luonmgw và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
# tách mảng X thành X train X test trong đó X train chứa 70% dữ liệu và tahcs y thành y train và y test trong đó y train chứa 70% dữ leieuj
# tạo 10 tập dữ liệu không chồng chéo nhau 


In [134]:
# BTVN4
import numpy as np
# tạo 1 mảng numpy có kích thức 150 x 5. giả sử mảng này chứa 150 mẫu dữ liệu 
# của sinh vienen  bao gồm chiều cao cân nặng tuổi , luonmgw và điểm trung bình
data = np.random.rand(150, 5)
# tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
x = data[:, :4]
y = data[:, 4]
print("X shape:", x.shape)
print("y shape:", y.shape)  
# tách mảng X thành X train X test trong đó X train chứa 70% dữ liệu và tahcs y thành y train và y test trong đó y train chứa 70% dữ leieuj
n_train = int(0.7 * len(x))
x_train = x[:n_train]
x_test  = x[n_train:]
y_train = y[:n_train]
y_test  = y[n_train:]
# tạo 10 tập dữ liệu không chồng chéo nhau 
datasets = np.array_split(data, 10)
print(f"Kích thước X: {x.shape}")
print(f"Kích thước y: {y.shape}")
print(f"Kích thước X_train: {x_train.shape}, X_test: {x_test.shape}")
print(f"Số lượng tập dữ liệu: {len(datasets)}")
print(f"Kích thước mỗi tập: {datasets[0].shape}")

X shape: (150, 4)
y shape: (150,)
Kích thước X: (150, 4)
Kích thước y: (150,)
Kích thước X_train: (105, 4), X_test: (45, 4)
Số lượng tập dữ liệu: 10
Kích thước mỗi tập: (15, 5)
