# DEEP LEARNING 
## PyTorch Basic

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

Sử dụng GPU và CUDA

In [3]:
torch.cuda.current_device

<function torch.cuda.current_device() -> int>

Dataset with pytorch

In [4]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [6]:
df.shape


(150, 6)

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Species'], axis=1).values
y = le.fit_transform(df['Species'].values)

# chia dữ liệu với test size 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

len(y_train)

120

In [8]:
Labels, counts = y_train.unique(return_counts=True)
print(Labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


# Tính đạo hàm bằng PyTorch

# cho y = 2x^4 + x^3 + 3x^2 + 5*x + 1

# tính y'

In [9]:
import torch


In [10]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)


tensor(2., requires_grad=True)
None


In [11]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [12]:
# Thực hiện lan truyền ngược và tính toán các gradient
y.backward()

In [13]:
# 8x^3 + 3x^2 + 6x + 5
x.grad

tensor(93.)

# BTVN

#### Cho y = 5x^5 + 6x^3 - 3x + 1

#### Cho biết độ dốc của da thức trên ở điểm nào


In [14]:
# BTVN

#### Cho y = 5x^5 + 6x^3 - 3x + 1
import torch
x = torch.tensor(1.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
print(y)
y.backward()
#### Cho biết độ dốc của da thức trên ở điểm nào
x.grad

tensor(9., grad_fn=<AddBackward0>)


tensor(40.)

# BTVN 02:

# Tạo 1 tensor có giá trị ban đầu bằng 2

# Định nghĩa hàm số và tính  gradient

# y  = x^3 + 2x^2 + 5x + 1

# Dùng phương pháp Gradient Descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

In [15]:
# BTVN 02:
import torch

x = torch.tensor(2.0, requires_grad=True)
alpha = 0.1

for i in range(10):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    x = x - alpha * x.grad
    x = x.detach().requires_grad_()
    
    print(x.item())

-0.5
-0.875
-1.2546875476837158
-1.7250847816467285
-2.427826166152954
-3.7249975204467773
-6.897680282592773
-18.912006378173828
-119.14640808105469
-4330.74755859375


# BTVN 03:

## Tạo 1 tập dữ giả lặp với x là số giờ tự học (ngẫu nhiên  từ 1 đến 10) và y là điểm số được tính theo công thức y = 3x + 5 + noise với noise là giá trị ngẫu nhiên nhỏ

1. Khởi tạo tham số w, b ngẫu nhiên với requires_grad=True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng để xem sự hội tụ mô hình

In [16]:
# BTVN 03:
import torch
# Tạo 1 tập dữ giả lặp với x là số giờ tự học (ngẫu nhiên  từ 1 đến 10) và y là điểm số được tính theo công thức y = 3x + 5 + noise với noise là giá trị ngẫu nhiên nhỏ
x = torch.rand(20) * 9 + 1
noise = torch.randn(20) * 0.5
y = 3*x + 5 + noise
# 1. Khởi tạo tham số w, b ngẫu nhiên với requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
# 2. Tính MSE
y_pred = w * x + b
mse = ((y_pred - y)**2).mean()
# 3. Tính Gradient
mse.backward()
# 4. Cập nhật tham số w và b bằng Gradient Descent với learning rate alpha = 0.01
alpha = 0.01
with torch.no_grad():
    w -= alpha * w.grad
    b -= alpha * b.grad
# 5. Lặp lại quá trình trên trong 100 vòng để xem sự hội tụ mô hình
for i in range(100):
    y_pred = w * x + b
    mse = ((y_pred - y)**2).mean()
    mse.backward()
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    w.grad.zero_()
    b.grad.zero_()
    if (i+1) % 10 == 0:
        print(f"Vòng {i+1}: loss={mse.item():.3f}, w={w.item():.3f}, b={b.item():.3f}")




Vòng 10: loss=6.641, w=4.030, b=-0.215
Vòng 20: loss=6.108, w=3.983, b=0.010
Vòng 30: loss=5.619, w=3.941, b=0.226
Vòng 40: loss=5.170, w=3.901, b=0.433
Vòng 50: loss=4.758, w=3.862, b=0.632
Vòng 60: loss=4.380, w=3.825, b=0.822
Vòng 70: loss=4.033, w=3.790, b=1.005
Vòng 80: loss=3.714, w=3.756, b=1.179
Vòng 90: loss=3.422, w=3.723, b=1.346
Vòng 100: loss=3.153, w=3.692, b=1.507


In [17]:
# Python with Tensor

In [18]:
import torch
import numpy as np

In [19]:
torch.__version__

'2.5.1+cu121'

In [20]:
# chuyển đổi mảng numpy sang tensor trong pytorch
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [21]:
x = torch.from_numpy(arr)
print(x)


tensor([1, 2, 3, 4, 5])


In [22]:
print(x.dtype)

torch.int64


In [23]:
print(x.type())

torch.LongTensor


In [24]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [25]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [26]:
# Copy and share memory

x = torch.tensor(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [27]:
arr[0] = 99
print(x)

tensor([1, 2, 3, 4, 5])


In [28]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [29]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN 4: Giải thích 2 trường hợp trên
-  Trường hợp 1: torch.from_numpy() tạo tensor dùng chung dữ liệu với NumPy array nên khi thay đổi NumPy array thì tensor cũng thay đổi theo
- Trường hopwj 2: torch.tensor() tạo tensor bằng cách sao chép dữ liệu nên tensor không bị ảnh hưởng khi NumPy array thay đổi

# BTVN 5: 

- `Tạo tensor với`
- `emty`
- `zeros`
- `ones`
- `random`
- `reshape với view `

In [30]:
# BTVN 5: 
# Tạo tensor với
import torch
# emty
a = torch.empty(2, 3)
print("empty:\n", a)
# zeros
b = torch.zeros(2, 3)
print("zeros:\n", b)
# ones
c = torch.ones(2, 3)
print("ones:\n", c)
# random
d = torch.rand(2, 3)
print("random:\n", d)
# reshape với view
e = torch.arange(0, 12).view(4, 3)
print("reshape với view:\n", e)

empty:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
random:
 tensor([[0.2732, 0.3924, 0.7908],
        [0.5700, 0.5697, 0.9768]])
reshape với view:
 tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
